#Pipeline name
name: Docker Deployment

#Trigger that execute this pipeline when new 
on:
    push:
        branches:
            - 'main'
jobs:
    Deploy:
        runs-on: ubuntu-latest

        steps:
            #Git repo code import into Github actions
            -
                name: Checkout
                uses: actions/checkout@v4

            -
                name: Set up QEMU
                uses: docker/setup-qemu-action@v3

            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

            -
                name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: vignesh2308m
                    password: dckr_pat_jMcUw9lgQOxC1TYDSAkzJRuVWZk
            -
                name: Build and push
                uses: docker/build-push-action@v5
                with:
                    push: true
                    tags: vignesh2308m/vignesh_flask_app:latest